### ISSUE TITLE
amount 검증 과정 필요함.

### ISSUE THREAD

**Issue by limdongjin** [paekjisoo/bbobanew#48]
https://github.com/paekjisoo/bbobanew/blob/336536387b58d8a27c151f7eeeca064699dc3aec/app/controllers/payment_controller.rb#L11

params로 넘어오는 값은 사용자가 충분히 조작할수있음

**Comment by changgwon** [comment]
입금되는 금액과 다르면 어차피 충전안됨

**Comment by limdongjin** [comment]
> 입금되는 금액과 다르면 어차피 충전안됨

Charge 디비는 조작 가능하자너!

**Comment by changgwon** [comment]
charge 디비로 충전하는 것 아님!

**Comment by limdongjin** [comment]
글쿠만 훌륭하군
