### ISSUE TITLE
Home Controller Authentication 안되어있음

### ISSUE THREAD

**Issue by limdongjin** [paekjisoo/bbobanew#51]
https://github.com/paekjisoo/bbobanew/blob/098aab83385c54758a2dbe2a8a1280a4f0afdbb6/app/controllers/home_controller.rb#L1-L263

current_user가 명시되어있는 액션의 경우에는 비회원일때 에러가 발생하게되서, 그나마 문제없는데...

changeState1, 3, filecheck 의 경우에는 오직 params[:id]만 조작하면 얼마든지 조작이 가능하게됨. 
또한 filedetail액션의 경우는 본인이 올리지 않은 타인의 파일까지 확인할수있다는 문제가 존재함. 어떠한 보안 코드가 존재하지않음

**Comment by changgwon** [comment]
read를 제외한 write될 수 있는 부분은 수정완료
