### ISSUE TITLE
누구나 Charge Delete를 수행할수있음.

### ISSUE THREAD

**Issue by limdongjin** [paekjisoo/bbobanew#53]
https://github.com/paekjisoo/bbobanew/blob/098aab83385c54758a2dbe2a8a1280a4f0afdbb6/app/controllers/payment_controller.rb#L25-L29

본인의 Charge가 아니더라도,,,, 심지어 비회원이어도!!!! 왜냐면 authenticate 코드가 없거등

**Comment by changgwon** [comment]
해결
