### ISSUE TITLE
누구나 프린트 내역을 확인할수있는 문제가 있음.

### ISSUE THREAD

**Issue by limdongjin** [paekjisoo/bbobanew#54]
https://github.com/paekjisoo/bbobanew/blob/098aab83385c54758a2dbe2a8a1280a4f0afdbb6/app/controllers/printer_controller.rb#L1-L16

자신의 프린트 내역뿐만 아니라, 다른 유저의 프린트 내역까지 누구나 확인할수있게됨

**Comment by changgwon** [comment]
안쓰는 코드 해결
